### ISSUE TITLE
Restrict CDC bootloader programming region

### ISSUE THREAD

**Issue by NicoHood** [abcminiuser/lufa#115]
Similar to HID this should also be implemented for CDC:
https://github.com/abcminiuser/lufa/commit/f0c5dfe8b8f47211f03454da036223d65e08249c

Additionally instead of 0xFFFF this an be used:
```
#if (FLASHEND > USHRT_MAX)
```
This is also worth to change in other bootloaders.

**Comment by abcminiuser** [comment]
Fixed in ba6d9c1a971db3c42bf0b054ebb64f72b3e3ddba.
