### ISSUE TITLE
Flush USB transactions for HID Bootloader

### ISSUE THREAD

**Issue by NicoHood** [abcminiuser/lufa#116]
Apply this patch also to the HID Bootloader:
https://github.com/abcminiuser/lufa/commit/e3988f19dda2345032f575f31f275693571d9267

https://github.com/abcminiuser/lufa/blob/master/Bootloaders/HID/BootloaderHID.c#L88

**Comment by abcminiuser** [comment]
Fixed in d6a528f9a03fe338e30d93f306e0482612e02e3e - added the delay to all the bootloaders, for good measure. Thanks!
