### ISSUE TITLE
CDC Class Driver fputc() return written character

### ISSUE THREAD

**Issue by NicoHood** [abcminiuser/lufa#119]
http://www.cplusplus.com/reference/cstdio/fputc/:
> On success, the character written is returned.

https://github.com/abcminiuser/lufa/blob/master/LUFA/Drivers/USB/Class/Device/CDCClassDevice.c#L326
```c
static int CDC_Device_putchar(char c,
                              FILE* Stream)
{
	return CDC_Device_SendByte((USB_ClassInfo_CDC_Device_t*)fdev_get_udata(Stream), c) ? _FDEV_ERR : 0;
}
```

Shouldn't it be `_FDEV_ERR : c;` then?

**Comment by abcminiuser** [comment]
Yes, it should. Fixed in 8802907ce274489690f8edf169454f750c8efe57 - thanks!
