### ISSUE TITLE
UC3 build fails due indiscrepancies

### ISSUE THREAD

**Issue by laid** [abcminiuser/lufa#123]
The UC3 code has some redundant PROGMEM related hooks in code as of build 170418 (as current AS7 extension):

* strlen_P
* Endpoint_Write_PStream_LE()
* Pipe_Write_PStream_LE()

**Comment by laid** [comment]
The workaround I am using (for not altering the LUFA build) is to to define all three in makefile / project options:

`-Dstrlen_P="strlen" -DEndpoint_Write_PStream_LE(...) -DPipe_Write_PStream_LE(...)`

**Comment by abcminiuser** [comment]
Hopefully fixed by https://github.com/abcminiuser/lufa/commit/2028e82e455a3d4caab3ad47b0c3a0815e1c1ae6. Can you please confirm?

**Comment by abcminiuser** [comment]
Closing for now, please re-open if the current fixes in HEAD are insufficient.
