### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by NicoHood** [abcminiuser/lufa#136]
Could we get a new release? It's been over a year now and many new fixes were introduced :)

**Comment by abcminiuser** [comment]
Sure, release schedule is basically just a "whenever the changes warrant it" at this point. Looking over the changelog there aren't too many big changes/fixes, but it has been a while since the last release. I might put in the new smart card class driver first, however.

**Comment by NicoHood** [comment]
*push*

**Comment by abcminiuser** [comment]
Oops, I'll do one now. I guess it's been long enough!

**Comment by abcminiuser** [comment]
Released 2021-01-30.

**Comment by gasparisaac** [comment]
@abcminiuser hey! just wondering what's the idea behind the versioning and releases in github? if we want to use the latest version, should we just pull 'master' branch or the 2021-01-30 tag? thanks for the maintenance work :)
