### ISSUE TITLE
How can I use USB hub with LUFA host driver?

### ISSUE THREAD

**Issue by slsvasu348** [abcminiuser/lufa#139]
I want to use hub with LUFA host driver. Is there any solution available?

**Comment by abcminiuser** [comment]
Unfortunately the USB AVRs that support host mode lack some of the registers needed for hub control, so it's unlikely you would be able to get it to work. Certainly not without an enormous effort to support multiple concurrent devices.

**Comment by slsvasu348** [comment]
We are porting it for our USB ip for nios-2 platform. So not any issue with lack of registers.
