### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by behrad2k** [abcminiuser/lufa#188]
i just get `avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=at90usb1287 -fshort-enums -fno-inline-small-functions -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DDMBS_ARCH_AVR8 -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DF_CPU=8000000UL -DUSE_LUFA_CONFIG_HEADER -IConfig/ -ILib/uip/ -ILib/FATFs/ -I. -I../../LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_USBKEY -DF_USB=8000000UL   -MMD -MP -MF obj/DHCPServerApp.d Lib/DHCPServerApp.c -o obj/DHCPServerApp.o
Lib/DHCPServerApp.c: In function 'DHCPServerApp_Init':
Lib/DHCPServerApp.c:53:29: error: assignment to 'struct uip_conn *' from incompatible pointer type 'struct uip_udp_conn *' [-Wincompatible-pointer-types]
   53 |         BroadcastConnection = uip_udp_new(&uip_broadcast_addr, HTONS(DHCP_CLIENT_PORT));
      |                             ^
make[2]: *** [../../LUFA/Build/DMBS/DMBS/gcc.mk:226: obj/DHCPServerApp.o] Error 1
make[2]: Leaving directory '/home/behrad/Downloads/lufa/lufa-LUFA-210130/Projects/Webserver'
make[1]: *** [makefile:33: Webserver/] Error 2
make[1]: Leaving directory '/home/behrad/Downloads/lufa/lufa-LUFA-210130/Projects'
make: *** [makefile:22: all] Error 2` when i try to compile

**Comment by abcminiuser** [comment]
Fixed in https://github.com/abcminiuser/lufa/commit/a13ca118d3987890b749a2a96a92f74771821f8a
