### ISSUE TITLE
The Serial_Init function documentation is confusing

### ISSUE THREAD

**Issue by matlo** [abcminiuser/lufa#43]
The documentation states:
>BaudRate Serial baud rate, in bits per second.
>DoubleSpeed Enables double speed mode when set, halving the sample time to double the baud rate.

One might think that setting BaudRate to X and DoubleSpeed to true should result in an actual baud rate of 2*X.

In fact the BaudRate argument has to be the actual baud rate.

**Comment by abcminiuser** [comment]
Good point matlo - fixed in be2df78637004801ea05902afe2b0e55da43ff47.
