### ISSUE TITLE
Support for large TWI reads

### ISSUE THREAD

**Issue by waldo3000** [abcminiuser/lufa#53]
Currently, TWI_ReadPacket and TWI_WritePacket use a uint8_t for the data packet length.  However, many EEPROMs allow reading sequential addresses over more than a 256 address range.  I would suggest changing:
   uint8_t Length
to:
   uint16_t Length

**Comment by abcminiuser** [comment]
Good idea; I'll patch this in master.

**Comment by abcminiuser** [comment]
Fixed in 7638128d47f90dafbbf8bc2454971afd726e005e.
