### ISSUE TITLE
OSX 10.11 Unable to open device

### ISSUE THREAD

**Issue by ghost** [abcminiuser/lufa#87]
OSX 10.11, built against 10.11 SDK, it states "unable to open device"  Not really sure how to proceed.

**Comment by abcminiuser** [comment]
Whoops, I've totally forgotten to take a look through the issue list for aaaggeeess. Can you confirm that patch fixes the issue, since I haven't got a MacOS machine to test it?

**Comment by darrelhunt** [comment]
I totally don't mind testing, I don't know code though.  So I remove the red lines, put in the green ones.  Whathe are the grey ones?

**Comment by eltang** [comment]
The gray text is comment text, which is not actual code. You can ignore it.

**Comment by abcminiuser** [comment]
PJRC programmer code has been rebased; closing for now until someone confirms this is still relevant with the latest HEAD.
