### ISSUE TITLE
LUFA fails to wake up host

### ISSUE THREAD

**Issue by eltang** [abcminiuser/lufa#98]
The following code seems to have no effect when run on an ATmega32U4 whose host is a Mac running Sierra.
```c
if (USB_DeviceState == DEVICE_STATE_Suspended)
    if (USB_Device_RemoteWakeupEnabled)
        USB_Device_SendRemoteWakeup();
```

**Comment by abcminiuser** [comment]
What is the state of `USB_Device_RemoteWakeupEnabled`?

Make sure you have enabled `USB_CONFIG_ATTR_REMOTEWAKEUP` in your configuration descriptor's `ConfigAttributes` element, along with the mandatory `USB_CONFIG_ATTR_RESERVED` attribute and (optional) `USB_CONFIG_ATTR_SELFPOWERED` attribute. Without this option, the host won't enable remote wakeup and you won't be able to trigger a wake from suspended mode.

**Comment by eltang** [comment]
They have respective values of `1` and `USB_CONFIG_ATTR_RESERVED | USB_CONFIG_ATTR_REMOTEWAKEUP`, just as expected. In the meantime, I've also discovered that the ATmega32U4 renders the mouse unable to wake up the computer as well.

**Comment by eltang** [comment]
I've found something even stranger. It turns out that the ATmega32U4 is able to wake up the computer, but only if it's been suspended for a long period of time.

**Comment by eltang** [comment]
Whoops, after some more rigorous testing I discovered that the problem is with my code and not with LUFA.
